QT       += \
    core gui \
    charts \
    datavisualization

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    common_utils.cpp \
    main.cpp \
    widget.cpp \
    window_barchart.cpp \
    window_cluster.cpp \
    window_covariance.cpp \
    window_ml.cpp \
    window_pca.cpp \
    window_scatter.cpp

HEADERS += \
    Eigen/Cholesky \
    Eigen/CholmodSupport \
    Eigen/Core \
    Eigen/Dense \
    Eigen/Eigen \
    Eigen/Eigenvalues \
    Eigen/Geometry \
    Eigen/Householder \
    Eigen/IterativeLinearSolvers \
    Eigen/Jacobi \
    Eigen/KLUSupport \
    Eigen/LU \
    Eigen/MetisSupport \
    Eigen/OrderingMethods \
    Eigen/PaStiXSupport \
    Eigen/PardisoSupport \
    Eigen/QR \
    Eigen/QtAlignedMalloc \
    Eigen/SPQRSupport \
    Eigen/SVD \
    Eigen/Sparse \
    Eigen/SparseCholesky \
    Eigen/SparseCore \
    Eigen/SparseLU \
    Eigen/SparseQR \
    Eigen/StdDeque \
    Eigen/StdList \
    Eigen/StdVector \
    Eigen/SuperLUSupport \
    Eigen/UmfPackSupport \
    Eigen/src/Cholesky/LDLT.h \
    Eigen/src/Cholesky/LLT.h \
    Eigen/src/Cholesky/LLT_LAPACKE.h \
    Eigen/src/CholmodSupport/CholmodSupport.h \
    Eigen/src/Core/ArithmeticSequence.h \
    Eigen/src/Core/Array.h \
    Eigen/src/Core/ArrayBase.h \
    Eigen/src/Core/ArrayWrapper.h \
    Eigen/src/Core/Assign.h \
    Eigen/src/Core/AssignEvaluator.h \
    Eigen/src/Core/Assign_MKL.h \
    Eigen/src/Core/BandMatrix.h \
    Eigen/src/Core/Block.h \
    Eigen/src/Core/BooleanRedux.h \
    Eigen/src/Core/CommaInitializer.h \
    Eigen/src/Core/ConditionEstimator.h \
    Eigen/src/Core/CoreEvaluators.h \
    Eigen/src/Core/CoreIterators.h \
    Eigen/src/Core/CwiseBinaryOp.h \
    Eigen/src/Core/CwiseNullaryOp.h \
    Eigen/src/Core/CwiseTernaryOp.h \
    Eigen/src/Core/CwiseUnaryOp.h \
    Eigen/src/Core/CwiseUnaryView.h \
    Eigen/src/Core/DenseBase.h \
    Eigen/src/Core/DenseCoeffsBase.h \
    Eigen/src/Core/DenseStorage.h \
    Eigen/src/Core/Diagonal.h \
    Eigen/src/Core/DiagonalMatrix.h \
    Eigen/src/Core/DiagonalProduct.h \
    Eigen/src/Core/Dot.h \
    Eigen/src/Core/EigenBase.h \
    Eigen/src/Core/ForceAlignedAccess.h \
    Eigen/src/Core/Fuzzy.h \
    Eigen/src/Core/GeneralProduct.h \
    Eigen/src/Core/GenericPacketMath.h \
    Eigen/src/Core/GlobalFunctions.h \
    Eigen/src/Core/IO.h \
    Eigen/src/Core/IndexedView.h \
    Eigen/src/Core/Inverse.h \
    Eigen/src/Core/Map.h \
    Eigen/src/Core/MapBase.h \
    Eigen/src/Core/MathFunctions.h \
    Eigen/src/Core/MathFunctionsImpl.h \
    Eigen/src/Core/Matrix.h \
    Eigen/src/Core/MatrixBase.h \
    Eigen/src/Core/NestByValue.h \
    Eigen/src/Core/NoAlias.h \
    Eigen/src/Core/NumTraits.h \
    Eigen/src/Core/PartialReduxEvaluator.h \
    Eigen/src/Core/PermutationMatrix.h \
    Eigen/src/Core/PlainObjectBase.h \
    Eigen/src/Core/Product.h \
    Eigen/src/Core/ProductEvaluators.h \
    Eigen/src/Core/Random.h \
    Eigen/src/Core/Redux.h \
    Eigen/src/Core/Ref.h \
    Eigen/src/Core/Replicate.h \
    Eigen/src/Core/Reshaped.h \
    Eigen/src/Core/ReturnByValue.h \
    Eigen/src/Core/Reverse.h \
    Eigen/src/Core/Select.h \
    Eigen/src/Core/SelfAdjointView.h \
    Eigen/src/Core/SelfCwiseBinaryOp.h \
    Eigen/src/Core/Solve.h \
    Eigen/src/Core/SolveTriangular.h \
    Eigen/src/Core/SolverBase.h \
    Eigen/src/Core/StableNorm.h \
    Eigen/src/Core/StlIterators.h \
    Eigen/src/Core/Stride.h \
    Eigen/src/Core/Swap.h \
    Eigen/src/Core/Transpose.h \
    Eigen/src/Core/Transpositions.h \
    Eigen/src/Core/TriangularMatrix.h \
    Eigen/src/Core/VectorBlock.h \
    Eigen/src/Core/VectorwiseOp.h \
    Eigen/src/Core/Visitor.h \
    Eigen/src/Core/arch/AVX/Complex.h \
    Eigen/src/Core/arch/AVX/MathFunctions.h \
    Eigen/src/Core/arch/AVX/PacketMath.h \
    Eigen/src/Core/arch/AVX/TypeCasting.h \
    Eigen/src/Core/arch/AVX512/Complex.h \
    Eigen/src/Core/arch/AVX512/MathFunctions.h \
    Eigen/src/Core/arch/AVX512/PacketMath.h \
    Eigen/src/Core/arch/AVX512/TypeCasting.h \
    Eigen/src/Core/arch/AltiVec/Complex.h \
    Eigen/src/Core/arch/AltiVec/MathFunctions.h \
    Eigen/src/Core/arch/AltiVec/MatrixProduct.h \
    Eigen/src/Core/arch/AltiVec/MatrixProductCommon.h \
    Eigen/src/Core/arch/AltiVec/MatrixProductMMA.h \
    Eigen/src/Core/arch/AltiVec/PacketMath.h \
    Eigen/src/Core/arch/CUDA/Complex.h \
    Eigen/src/Core/arch/Default/BFloat16.h \
    Eigen/src/Core/arch/Default/ConjHelper.h \
    Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h \
    Eigen/src/Core/arch/Default/GenericPacketMathFunctionsFwd.h \
    Eigen/src/Core/arch/Default/Half.h \
    Eigen/src/Core/arch/Default/Settings.h \
    Eigen/src/Core/arch/Default/TypeCasting.h \
    Eigen/src/Core/arch/GPU/MathFunctions.h \
    Eigen/src/Core/arch/GPU/PacketMath.h \
    Eigen/src/Core/arch/GPU/TypeCasting.h \
    Eigen/src/Core/arch/HIP/hcc/math_constants.h \
    Eigen/src/Core/arch/MSA/Complex.h \
    Eigen/src/Core/arch/MSA/MathFunctions.h \
    Eigen/src/Core/arch/MSA/PacketMath.h \
    Eigen/src/Core/arch/NEON/Complex.h \
    Eigen/src/Core/arch/NEON/GeneralBlockPanelKernel.h \
    Eigen/src/Core/arch/NEON/MathFunctions.h \
    Eigen/src/Core/arch/NEON/PacketMath.h \
    Eigen/src/Core/arch/NEON/TypeCasting.h \
    Eigen/src/Core/arch/SSE/Complex.h \
    Eigen/src/Core/arch/SSE/MathFunctions.h \
    Eigen/src/Core/arch/SSE/PacketMath.h \
    Eigen/src/Core/arch/SSE/TypeCasting.h \
    Eigen/src/Core/arch/SVE/MathFunctions.h \
    Eigen/src/Core/arch/SVE/PacketMath.h \
    Eigen/src/Core/arch/SVE/TypeCasting.h \
    Eigen/src/Core/arch/SYCL/InteropHeaders.h \
    Eigen/src/Core/arch/SYCL/MathFunctions.h \
    Eigen/src/Core/arch/SYCL/PacketMath.h \
    Eigen/src/Core/arch/SYCL/SyclMemoryModel.h \
    Eigen/src/Core/arch/SYCL/TypeCasting.h \
    Eigen/src/Core/arch/ZVector/Complex.h \
    Eigen/src/Core/arch/ZVector/MathFunctions.h \
    Eigen/src/Core/arch/ZVector/PacketMath.h \
    Eigen/src/Core/functors/AssignmentFunctors.h \
    Eigen/src/Core/functors/BinaryFunctors.h \
    Eigen/src/Core/functors/NullaryFunctors.h \
    Eigen/src/Core/functors/StlFunctors.h \
    Eigen/src/Core/functors/TernaryFunctors.h \
    Eigen/src/Core/functors/UnaryFunctors.h \
    Eigen/src/Core/products/GeneralBlockPanelKernel.h \
    Eigen/src/Core/products/GeneralMatrixMatrix.h \
    Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
    Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
    Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
    Eigen/src/Core/products/GeneralMatrixVector.h \
    Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
    Eigen/src/Core/products/Parallelizer.h \
    Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
    Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
    Eigen/src/Core/products/SelfadjointMatrixVector.h \
    Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
    Eigen/src/Core/products/SelfadjointProduct.h \
    Eigen/src/Core/products/SelfadjointRank2Update.h \
    Eigen/src/Core/products/TriangularMatrixMatrix.h \
    Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
    Eigen/src/Core/products/TriangularMatrixVector.h \
    Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
    Eigen/src/Core/products/TriangularSolverMatrix.h \
    Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
    Eigen/src/Core/products/TriangularSolverVector.h \
    Eigen/src/Core/util/BlasUtil.h \
    Eigen/src/Core/util/ConfigureVectorization.h \
    Eigen/src/Core/util/Constants.h \
    Eigen/src/Core/util/DisableStupidWarnings.h \
    Eigen/src/Core/util/ForwardDeclarations.h \
    Eigen/src/Core/util/IndexedViewHelper.h \
    Eigen/src/Core/util/IntegralConstant.h \
    Eigen/src/Core/util/MKL_support.h \
    Eigen/src/Core/util/Macros.h \
    Eigen/src/Core/util/Memory.h \
    Eigen/src/Core/util/Meta.h \
    Eigen/src/Core/util/NonMPL2.h \
    Eigen/src/Core/util/ReenableStupidWarnings.h \
    Eigen/src/Core/util/ReshapedHelper.h \
    Eigen/src/Core/util/StaticAssert.h \
    Eigen/src/Core/util/SymbolicIndex.h \
    Eigen/src/Core/util/XprHelper.h \
    Eigen/src/Eigenvalues/ComplexEigenSolver.h \
    Eigen/src/Eigenvalues/ComplexSchur.h \
    Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
    Eigen/src/Eigenvalues/EigenSolver.h \
    Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
    Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
    Eigen/src/Eigenvalues/HessenbergDecomposition.h \
    Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
    Eigen/src/Eigenvalues/RealQZ.h \
    Eigen/src/Eigenvalues/RealSchur.h \
    Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
    Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
    Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
    Eigen/src/Eigenvalues/Tridiagonalization.h \
    Eigen/src/Geometry/AlignedBox.h \
    Eigen/src/Geometry/AngleAxis.h \
    Eigen/src/Geometry/EulerAngles.h \
    Eigen/src/Geometry/Homogeneous.h \
    Eigen/src/Geometry/Hyperplane.h \
    Eigen/src/Geometry/OrthoMethods.h \
    Eigen/src/Geometry/ParametrizedLine.h \
    Eigen/src/Geometry/Quaternion.h \
    Eigen/src/Geometry/Rotation2D.h \
    Eigen/src/Geometry/RotationBase.h \
    Eigen/src/Geometry/Scaling.h \
    Eigen/src/Geometry/Transform.h \
    Eigen/src/Geometry/Translation.h \
    Eigen/src/Geometry/Umeyama.h \
    Eigen/src/Geometry/arch/Geometry_SIMD.h \
    Eigen/src/Householder/BlockHouseholder.h \
    Eigen/src/Householder/Householder.h \
    Eigen/src/Householder/HouseholderSequence.h \
    Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
    Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
    Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
    Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h \
    Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
    Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
    Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h \
    Eigen/src/IterativeLinearSolvers/SolveWithGuess.h \
    Eigen/src/Jacobi/Jacobi.h \
    Eigen/src/KLUSupport/KLUSupport.h \
    Eigen/src/LU/Determinant.h \
    Eigen/src/LU/FullPivLU.h \
    Eigen/src/LU/InverseImpl.h \
    Eigen/src/LU/PartialPivLU.h \
    Eigen/src/LU/PartialPivLU_LAPACKE.h \
    Eigen/src/LU/arch/InverseSize4.h \
    Eigen/src/MetisSupport/MetisSupport.h \
    Eigen/src/OrderingMethods/Amd.h \
    Eigen/src/OrderingMethods/Eigen_Colamd.h \
    Eigen/src/OrderingMethods/Ordering.h \
    Eigen/src/PaStiXSupport/PaStiXSupport.h \
    Eigen/src/PardisoSupport/PardisoSupport.h \
    Eigen/src/QR/ColPivHouseholderQR.h \
    Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
    Eigen/src/QR/CompleteOrthogonalDecomposition.h \
    Eigen/src/QR/FullPivHouseholderQR.h \
    Eigen/src/QR/HouseholderQR.h \
    Eigen/src/QR/HouseholderQR_LAPACKE.h \
    Eigen/src/SPQRSupport/SuiteSparseQRSupport.h \
    Eigen/src/SVD/BDCSVD.h \
    Eigen/src/SVD/JacobiSVD.h \
    Eigen/src/SVD/JacobiSVD_LAPACKE.h \
    Eigen/src/SVD/SVDBase.h \
    Eigen/src/SVD/UpperBidiagonalization.h \
    Eigen/src/SparseCholesky/SimplicialCholesky.h \
    Eigen/src/SparseCholesky/SimplicialCholesky_impl.h \
    Eigen/src/SparseCore/AmbiVector.h \
    Eigen/src/SparseCore/CompressedStorage.h \
    Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
    Eigen/src/SparseCore/MappedSparseMatrix.h \
    Eigen/src/SparseCore/SparseAssign.h \
    Eigen/src/SparseCore/SparseBlock.h \
    Eigen/src/SparseCore/SparseColEtree.h \
    Eigen/src/SparseCore/SparseCompressedBase.h \
    Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
    Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
    Eigen/src/SparseCore/SparseDenseProduct.h \
    Eigen/src/SparseCore/SparseDiagonalProduct.h \
    Eigen/src/SparseCore/SparseDot.h \
    Eigen/src/SparseCore/SparseFuzzy.h \
    Eigen/src/SparseCore/SparseMap.h \
    Eigen/src/SparseCore/SparseMatrix.h \
    Eigen/src/SparseCore/SparseMatrixBase.h \
    Eigen/src/SparseCore/SparsePermutation.h \
    Eigen/src/SparseCore/SparseProduct.h \
    Eigen/src/SparseCore/SparseRedux.h \
    Eigen/src/SparseCore/SparseRef.h \
    Eigen/src/SparseCore/SparseSelfAdjointView.h \
    Eigen/src/SparseCore/SparseSolverBase.h \
    Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
    Eigen/src/SparseCore/SparseTranspose.h \
    Eigen/src/SparseCore/SparseTriangularView.h \
    Eigen/src/SparseCore/SparseUtil.h \
    Eigen/src/SparseCore/SparseVector.h \
    Eigen/src/SparseCore/SparseView.h \
    Eigen/src/SparseCore/TriangularSolver.h \
    Eigen/src/SparseLU/SparseLU.h \
    Eigen/src/SparseLU/SparseLUImpl.h \
    Eigen/src/SparseLU/SparseLU_Memory.h \
    Eigen/src/SparseLU/SparseLU_Structs.h \
    Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h \
    Eigen/src/SparseLU/SparseLU_Utils.h \
    Eigen/src/SparseLU/SparseLU_column_bmod.h \
    Eigen/src/SparseLU/SparseLU_column_dfs.h \
    Eigen/src/SparseLU/SparseLU_copy_to_ucol.h \
    Eigen/src/SparseLU/SparseLU_gemm_kernel.h \
    Eigen/src/SparseLU/SparseLU_heap_relax_snode.h \
    Eigen/src/SparseLU/SparseLU_kernel_bmod.h \
    Eigen/src/SparseLU/SparseLU_panel_bmod.h \
    Eigen/src/SparseLU/SparseLU_panel_dfs.h \
    Eigen/src/SparseLU/SparseLU_pivotL.h \
    Eigen/src/SparseLU/SparseLU_pruneL.h \
    Eigen/src/SparseLU/SparseLU_relax_snode.h \
    Eigen/src/SparseQR/SparseQR.h \
    Eigen/src/StlSupport/StdDeque.h \
    Eigen/src/StlSupport/StdList.h \
    Eigen/src/StlSupport/StdVector.h \
    Eigen/src/StlSupport/details.h \
    Eigen/src/SuperLUSupport/SuperLUSupport.h \
    Eigen/src/UmfPackSupport/UmfPackSupport.h \
    Eigen/src/misc/Image.h \
    Eigen/src/misc/Kernel.h \
    Eigen/src/misc/RealSvd2x2.h \
    Eigen/src/misc/blas.h \
    Eigen/src/misc/lapack.h \
    Eigen/src/misc/lapacke.h \
    Eigen/src/misc/lapacke_mangling.h \
    Eigen/src/plugins/ArrayCwiseBinaryOps.h \
    Eigen/src/plugins/ArrayCwiseUnaryOps.h \
    Eigen/src/plugins/BlockMethods.h \
    Eigen/src/plugins/CommonCwiseBinaryOps.h \
    Eigen/src/plugins/CommonCwiseUnaryOps.h \
    Eigen/src/plugins/IndexedViewMethods.h \
    Eigen/src/plugins/MatrixCwiseBinaryOps.h \
    Eigen/src/plugins/MatrixCwiseUnaryOps.h \
    Eigen/src/plugins/ReshapedMethods.h \
    include/common_utils.h \
    include/needed_algo/Eigen/Cholesky \
    include/needed_algo/Eigen/CholmodSupport \
    include/needed_algo/Eigen/Core \
    include/needed_algo/Eigen/Dense \
    include/needed_algo/Eigen/Eigen \
    include/needed_algo/Eigen/Eigenvalues \
    include/needed_algo/Eigen/Geometry \
    include/needed_algo/Eigen/Householder \
    include/needed_algo/Eigen/IterativeLinearSolvers \
    include/needed_algo/Eigen/Jacobi \
    include/needed_algo/Eigen/KLUSupport \
    include/needed_algo/Eigen/LU \
    include/needed_algo/Eigen/MetisSupport \
    include/needed_algo/Eigen/OrderingMethods \
    include/needed_algo/Eigen/PaStiXSupport \
    include/needed_algo/Eigen/PardisoSupport \
    include/needed_algo/Eigen/QR \
    include/needed_algo/Eigen/QtAlignedMalloc \
    include/needed_algo/Eigen/SPQRSupport \
    include/needed_algo/Eigen/SVD \
    include/needed_algo/Eigen/Sparse \
    include/needed_algo/Eigen/SparseCholesky \
    include/needed_algo/Eigen/SparseCore \
    include/needed_algo/Eigen/SparseLU \
    include/needed_algo/Eigen/SparseQR \
    include/needed_algo/Eigen/StdDeque \
    include/needed_algo/Eigen/StdList \
    include/needed_algo/Eigen/StdVector \
    include/needed_algo/Eigen/SuperLUSupport \
    include/needed_algo/Eigen/UmfPackSupport \
    include/needed_algo/Eigen/src/Cholesky/LDLT.h \
    include/needed_algo/Eigen/src/Cholesky/LLT.h \
    include/needed_algo/Eigen/src/Cholesky/LLT_LAPACKE.h \
    include/needed_algo/Eigen/src/CholmodSupport/CholmodSupport.h \
    include/needed_algo/Eigen/src/Core/ArithmeticSequence.h \
    include/needed_algo/Eigen/src/Core/Array.h \
    include/needed_algo/Eigen/src/Core/ArrayBase.h \
    include/needed_algo/Eigen/src/Core/ArrayWrapper.h \
    include/needed_algo/Eigen/src/Core/Assign.h \
    include/needed_algo/Eigen/src/Core/AssignEvaluator.h \
    include/needed_algo/Eigen/src/Core/Assign_MKL.h \
    include/needed_algo/Eigen/src/Core/BandMatrix.h \
    include/needed_algo/Eigen/src/Core/Block.h \
    include/needed_algo/Eigen/src/Core/BooleanRedux.h \
    include/needed_algo/Eigen/src/Core/CommaInitializer.h \
    include/needed_algo/Eigen/src/Core/ConditionEstimator.h \
    include/needed_algo/Eigen/src/Core/CoreEvaluators.h \
    include/needed_algo/Eigen/src/Core/CoreIterators.h \
    include/needed_algo/Eigen/src/Core/CwiseBinaryOp.h \
    include/needed_algo/Eigen/src/Core/CwiseNullaryOp.h \
    include/needed_algo/Eigen/src/Core/CwiseTernaryOp.h \
    include/needed_algo/Eigen/src/Core/CwiseUnaryOp.h \
    include/needed_algo/Eigen/src/Core/CwiseUnaryView.h \
    include/needed_algo/Eigen/src/Core/DenseBase.h \
    include/needed_algo/Eigen/src/Core/DenseCoeffsBase.h \
    include/needed_algo/Eigen/src/Core/DenseStorage.h \
    include/needed_algo/Eigen/src/Core/Diagonal.h \
    include/needed_algo/Eigen/src/Core/DiagonalMatrix.h \
    include/needed_algo/Eigen/src/Core/DiagonalProduct.h \
    include/needed_algo/Eigen/src/Core/Dot.h \
    include/needed_algo/Eigen/src/Core/EigenBase.h \
    include/needed_algo/Eigen/src/Core/ForceAlignedAccess.h \
    include/needed_algo/Eigen/src/Core/Fuzzy.h \
    include/needed_algo/Eigen/src/Core/GeneralProduct.h \
    include/needed_algo/Eigen/src/Core/GenericPacketMath.h \
    include/needed_algo/Eigen/src/Core/GlobalFunctions.h \
    include/needed_algo/Eigen/src/Core/IO.h \
    include/needed_algo/Eigen/src/Core/IndexedView.h \
    include/needed_algo/Eigen/src/Core/Inverse.h \
    include/needed_algo/Eigen/src/Core/Map.h \
    include/needed_algo/Eigen/src/Core/MapBase.h \
    include/needed_algo/Eigen/src/Core/MathFunctions.h \
    include/needed_algo/Eigen/src/Core/MathFunctionsImpl.h \
    include/needed_algo/Eigen/src/Core/Matrix.h \
    include/needed_algo/Eigen/src/Core/MatrixBase.h \
    include/needed_algo/Eigen/src/Core/NestByValue.h \
    include/needed_algo/Eigen/src/Core/NoAlias.h \
    include/needed_algo/Eigen/src/Core/NumTraits.h \
    include/needed_algo/Eigen/src/Core/PartialReduxEvaluator.h \
    include/needed_algo/Eigen/src/Core/PermutationMatrix.h \
    include/needed_algo/Eigen/src/Core/PlainObjectBase.h \
    include/needed_algo/Eigen/src/Core/Product.h \
    include/needed_algo/Eigen/src/Core/ProductEvaluators.h \
    include/needed_algo/Eigen/src/Core/Random.h \
    include/needed_algo/Eigen/src/Core/Redux.h \
    include/needed_algo/Eigen/src/Core/Ref.h \
    include/needed_algo/Eigen/src/Core/Replicate.h \
    include/needed_algo/Eigen/src/Core/Reshaped.h \
    include/needed_algo/Eigen/src/Core/ReturnByValue.h \
    include/needed_algo/Eigen/src/Core/Reverse.h \
    include/needed_algo/Eigen/src/Core/Select.h \
    include/needed_algo/Eigen/src/Core/SelfAdjointView.h \
    include/needed_algo/Eigen/src/Core/SelfCwiseBinaryOp.h \
    include/needed_algo/Eigen/src/Core/Solve.h \
    include/needed_algo/Eigen/src/Core/SolveTriangular.h \
    include/needed_algo/Eigen/src/Core/SolverBase.h \
    include/needed_algo/Eigen/src/Core/StableNorm.h \
    include/needed_algo/Eigen/src/Core/StlIterators.h \
    include/needed_algo/Eigen/src/Core/Stride.h \
    include/needed_algo/Eigen/src/Core/Swap.h \
    include/needed_algo/Eigen/src/Core/Transpose.h \
    include/needed_algo/Eigen/src/Core/Transpositions.h \
    include/needed_algo/Eigen/src/Core/TriangularMatrix.h \
    include/needed_algo/Eigen/src/Core/VectorBlock.h \
    include/needed_algo/Eigen/src/Core/VectorwiseOp.h \
    include/needed_algo/Eigen/src/Core/Visitor.h \
    include/needed_algo/Eigen/src/Core/arch/AVX/Complex.h \
    include/needed_algo/Eigen/src/Core/arch/AVX/MathFunctions.h \
    include/needed_algo/Eigen/src/Core/arch/AVX/PacketMath.h \
    include/needed_algo/Eigen/src/Core/arch/AVX/TypeCasting.h \
    include/needed_algo/Eigen/src/Core/arch/AVX512/Complex.h \
    include/needed_algo/Eigen/src/Core/arch/AVX512/MathFunctions.h \
    include/needed_algo/Eigen/src/Core/arch/AVX512/PacketMath.h \
    include/needed_algo/Eigen/src/Core/arch/AVX512/TypeCasting.h \
    include/needed_algo/Eigen/src/Core/arch/AltiVec/Complex.h \
    include/needed_algo/Eigen/src/Core/arch/AltiVec/MathFunctions.h \
    include/needed_algo/Eigen/src/Core/arch/AltiVec/MatrixProduct.h \
    include/needed_algo/Eigen/src/Core/arch/AltiVec/MatrixProductCommon.h \
    include/needed_algo/Eigen/src/Core/arch/AltiVec/MatrixProductMMA.h \
    include/needed_algo/Eigen/src/Core/arch/AltiVec/PacketMath.h \
    include/needed_algo/Eigen/src/Core/arch/CUDA/Complex.h \
    include/needed_algo/Eigen/src/Core/arch/Default/BFloat16.h \
    include/needed_algo/Eigen/src/Core/arch/Default/ConjHelper.h \
    include/needed_algo/Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h \
    include/needed_algo/Eigen/src/Core/arch/Default/GenericPacketMathFunctionsFwd.h \
    include/needed_algo/Eigen/src/Core/arch/Default/Half.h \
    include/needed_algo/Eigen/src/Core/arch/Default/Settings.h \
    include/needed_algo/Eigen/src/Core/arch/Default/TypeCasting.h \
    include/needed_algo/Eigen/src/Core/arch/GPU/MathFunctions.h \
    include/needed_algo/Eigen/src/Core/arch/GPU/PacketMath.h \
    include/needed_algo/Eigen/src/Core/arch/GPU/TypeCasting.h \
    include/needed_algo/Eigen/src/Core/arch/HIP/hcc/math_constants.h \
    include/needed_algo/Eigen/src/Core/arch/MSA/Complex.h \
    include/needed_algo/Eigen/src/Core/arch/MSA/MathFunctions.h \
    include/needed_algo/Eigen/src/Core/arch/MSA/PacketMath.h \
    include/needed_algo/Eigen/src/Core/arch/NEON/Complex.h \
    include/needed_algo/Eigen/src/Core/arch/NEON/GeneralBlockPanelKernel.h \
    include/needed_algo/Eigen/src/Core/arch/NEON/MathFunctions.h \
    include/needed_algo/Eigen/src/Core/arch/NEON/PacketMath.h \
    include/needed_algo/Eigen/src/Core/arch/NEON/TypeCasting.h \
    include/needed_algo/Eigen/src/Core/arch/SSE/Complex.h \
    include/needed_algo/Eigen/src/Core/arch/SSE/MathFunctions.h \
    include/needed_algo/Eigen/src/Core/arch/SSE/PacketMath.h \
    include/needed_algo/Eigen/src/Core/arch/SSE/TypeCasting.h \
    include/needed_algo/Eigen/src/Core/arch/SVE/MathFunctions.h \
    include/needed_algo/Eigen/src/Core/arch/SVE/PacketMath.h \
    include/needed_algo/Eigen/src/Core/arch/SVE/TypeCasting.h \
    include/needed_algo/Eigen/src/Core/arch/SYCL/InteropHeaders.h \
    include/needed_algo/Eigen/src/Core/arch/SYCL/MathFunctions.h \
    include/needed_algo/Eigen/src/Core/arch/SYCL/PacketMath.h \
    include/needed_algo/Eigen/src/Core/arch/SYCL/SyclMemoryModel.h \
    include/needed_algo/Eigen/src/Core/arch/SYCL/TypeCasting.h \
    include/needed_algo/Eigen/src/Core/arch/ZVector/Complex.h \
    include/needed_algo/Eigen/src/Core/arch/ZVector/MathFunctions.h \
    include/needed_algo/Eigen/src/Core/arch/ZVector/PacketMath.h \
    include/needed_algo/Eigen/src/Core/functors/AssignmentFunctors.h \
    include/needed_algo/Eigen/src/Core/functors/BinaryFunctors.h \
    include/needed_algo/Eigen/src/Core/functors/NullaryFunctors.h \
    include/needed_algo/Eigen/src/Core/functors/StlFunctors.h \
    include/needed_algo/Eigen/src/Core/functors/TernaryFunctors.h \
    include/needed_algo/Eigen/src/Core/functors/UnaryFunctors.h \
    include/needed_algo/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
    include/needed_algo/Eigen/src/Core/products/GeneralMatrixMatrix.h \
    include/needed_algo/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
    include/needed_algo/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
    include/needed_algo/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
    include/needed_algo/Eigen/src/Core/products/GeneralMatrixVector.h \
    include/needed_algo/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
    include/needed_algo/Eigen/src/Core/products/Parallelizer.h \
    include/needed_algo/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
    include/needed_algo/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
    include/needed_algo/Eigen/src/Core/products/SelfadjointMatrixVector.h \
    include/needed_algo/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
    include/needed_algo/Eigen/src/Core/products/SelfadjointProduct.h \
    include/needed_algo/Eigen/src/Core/products/SelfadjointRank2Update.h \
    include/needed_algo/Eigen/src/Core/products/TriangularMatrixMatrix.h \
    include/needed_algo/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
    include/needed_algo/Eigen/src/Core/products/TriangularMatrixVector.h \
    include/needed_algo/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
    include/needed_algo/Eigen/src/Core/products/TriangularSolverMatrix.h \
    include/needed_algo/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
    include/needed_algo/Eigen/src/Core/products/TriangularSolverVector.h \
    include/needed_algo/Eigen/src/Core/util/BlasUtil.h \
    include/needed_algo/Eigen/src/Core/util/ConfigureVectorization.h \
    include/needed_algo/Eigen/src/Core/util/Constants.h \
    include/needed_algo/Eigen/src/Core/util/DisableStupidWarnings.h \
    include/needed_algo/Eigen/src/Core/util/ForwardDeclarations.h \
    include/needed_algo/Eigen/src/Core/util/IndexedViewHelper.h \
    include/needed_algo/Eigen/src/Core/util/IntegralConstant.h \
    include/needed_algo/Eigen/src/Core/util/MKL_support.h \
    include/needed_algo/Eigen/src/Core/util/Macros.h \
    include/needed_algo/Eigen/src/Core/util/Memory.h \
    include/needed_algo/Eigen/src/Core/util/Meta.h \
    include/needed_algo/Eigen/src/Core/util/NonMPL2.h \
    include/needed_algo/Eigen/src/Core/util/ReenableStupidWarnings.h \
    include/needed_algo/Eigen/src/Core/util/ReshapedHelper.h \
    include/needed_algo/Eigen/src/Core/util/StaticAssert.h \
    include/needed_algo/Eigen/src/Core/util/SymbolicIndex.h \
    include/needed_algo/Eigen/src/Core/util/XprHelper.h \
    include/needed_algo/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
    include/needed_algo/Eigen/src/Eigenvalues/ComplexSchur.h \
    include/needed_algo/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
    include/needed_algo/Eigen/src/Eigenvalues/EigenSolver.h \
    include/needed_algo/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
    include/needed_algo/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
    include/needed_algo/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
    include/needed_algo/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
    include/needed_algo/Eigen/src/Eigenvalues/RealQZ.h \
    include/needed_algo/Eigen/src/Eigenvalues/RealSchur.h \
    include/needed_algo/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
    include/needed_algo/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
    include/needed_algo/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
    include/needed_algo/Eigen/src/Eigenvalues/Tridiagonalization.h \
    include/needed_algo/Eigen/src/Geometry/AlignedBox.h \
    include/needed_algo/Eigen/src/Geometry/AngleAxis.h \
    include/needed_algo/Eigen/src/Geometry/EulerAngles.h \
    include/needed_algo/Eigen/src/Geometry/Homogeneous.h \
    include/needed_algo/Eigen/src/Geometry/Hyperplane.h \
    include/needed_algo/Eigen/src/Geometry/OrthoMethods.h \
    include/needed_algo/Eigen/src/Geometry/ParametrizedLine.h \
    include/needed_algo/Eigen/src/Geometry/Quaternion.h \
    include/needed_algo/Eigen/src/Geometry/Rotation2D.h \
    include/needed_algo/Eigen/src/Geometry/RotationBase.h \
    include/needed_algo/Eigen/src/Geometry/Scaling.h \
    include/needed_algo/Eigen/src/Geometry/Transform.h \
    include/needed_algo/Eigen/src/Geometry/Translation.h \
    include/needed_algo/Eigen/src/Geometry/Umeyama.h \
    include/needed_algo/Eigen/src/Geometry/arch/Geometry_SIMD.h \
    include/needed_algo/Eigen/src/Householder/BlockHouseholder.h \
    include/needed_algo/Eigen/src/Householder/Householder.h \
    include/needed_algo/Eigen/src/Householder/HouseholderSequence.h \
    include/needed_algo/Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
    include/needed_algo/Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
    include/needed_algo/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
    include/needed_algo/Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h \
    include/needed_algo/Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
    include/needed_algo/Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
    include/needed_algo/Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h \
    include/needed_algo/Eigen/src/IterativeLinearSolvers/SolveWithGuess.h \
    include/needed_algo/Eigen/src/Jacobi/Jacobi.h \
    include/needed_algo/Eigen/src/KLUSupport/KLUSupport.h \
    include/needed_algo/Eigen/src/LU/Determinant.h \
    include/needed_algo/Eigen/src/LU/FullPivLU.h \
    include/needed_algo/Eigen/src/LU/InverseImpl.h \
    include/needed_algo/Eigen/src/LU/PartialPivLU.h \
    include/needed_algo/Eigen/src/LU/PartialPivLU_LAPACKE.h \
    include/needed_algo/Eigen/src/LU/arch/InverseSize4.h \
    include/needed_algo/Eigen/src/MetisSupport/MetisSupport.h \
    include/needed_algo/Eigen/src/OrderingMethods/Amd.h \
    include/needed_algo/Eigen/src/OrderingMethods/Eigen_Colamd.h \
    include/needed_algo/Eigen/src/OrderingMethods/Ordering.h \
    include/needed_algo/Eigen/src/PaStiXSupport/PaStiXSupport.h \
    include/needed_algo/Eigen/src/PardisoSupport/PardisoSupport.h \
    include/needed_algo/Eigen/src/QR/ColPivHouseholderQR.h \
    include/needed_algo/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
    include/needed_algo/Eigen/src/QR/CompleteOrthogonalDecomposition.h \
    include/needed_algo/Eigen/src/QR/FullPivHouseholderQR.h \
    include/needed_algo/Eigen/src/QR/HouseholderQR.h \
    include/needed_algo/Eigen/src/QR/HouseholderQR_LAPACKE.h \
    include/needed_algo/Eigen/src/SPQRSupport/SuiteSparseQRSupport.h \
    include/needed_algo/Eigen/src/SVD/BDCSVD.h \
    include/needed_algo/Eigen/src/SVD/JacobiSVD.h \
    include/needed_algo/Eigen/src/SVD/JacobiSVD_LAPACKE.h \
    include/needed_algo/Eigen/src/SVD/SVDBase.h \
    include/needed_algo/Eigen/src/SVD/UpperBidiagonalization.h \
    include/needed_algo/Eigen/src/SparseCholesky/SimplicialCholesky.h \
    include/needed_algo/Eigen/src/SparseCholesky/SimplicialCholesky_impl.h \
    include/needed_algo/Eigen/src/SparseCore/AmbiVector.h \
    include/needed_algo/Eigen/src/SparseCore/CompressedStorage.h \
    include/needed_algo/Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
    include/needed_algo/Eigen/src/SparseCore/MappedSparseMatrix.h \
    include/needed_algo/Eigen/src/SparseCore/SparseAssign.h \
    include/needed_algo/Eigen/src/SparseCore/SparseBlock.h \
    include/needed_algo/Eigen/src/SparseCore/SparseColEtree.h \
    include/needed_algo/Eigen/src/SparseCore/SparseCompressedBase.h \
    include/needed_algo/Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
    include/needed_algo/Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
    include/needed_algo/Eigen/src/SparseCore/SparseDenseProduct.h \
    include/needed_algo/Eigen/src/SparseCore/SparseDiagonalProduct.h \
    include/needed_algo/Eigen/src/SparseCore/SparseDot.h \
    include/needed_algo/Eigen/src/SparseCore/SparseFuzzy.h \
    include/needed_algo/Eigen/src/SparseCore/SparseMap.h \
    include/needed_algo/Eigen/src/SparseCore/SparseMatrix.h \
    include/needed_algo/Eigen/src/SparseCore/SparseMatrixBase.h \
    include/needed_algo/Eigen/src/SparseCore/SparsePermutation.h \
    include/needed_algo/Eigen/src/SparseCore/SparseProduct.h \
    include/needed_algo/Eigen/src/SparseCore/SparseRedux.h \
    include/needed_algo/Eigen/src/SparseCore/SparseRef.h \
    include/needed_algo/Eigen/src/SparseCore/SparseSelfAdjointView.h \
    include/needed_algo/Eigen/src/SparseCore/SparseSolverBase.h \
    include/needed_algo/Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
    include/needed_algo/Eigen/src/SparseCore/SparseTranspose.h \
    include/needed_algo/Eigen/src/SparseCore/SparseTriangularView.h \
    include/needed_algo/Eigen/src/SparseCore/SparseUtil.h \
    include/needed_algo/Eigen/src/SparseCore/SparseVector.h \
    include/needed_algo/Eigen/src/SparseCore/SparseView.h \
    include/needed_algo/Eigen/src/SparseCore/TriangularSolver.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLUImpl.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_Memory.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_Structs.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_Utils.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_column_bmod.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_column_dfs.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_copy_to_ucol.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_gemm_kernel.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_kernel_bmod.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_panel_bmod.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_panel_dfs.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_pivotL.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_pruneL.h \
    include/needed_algo/Eigen/src/SparseLU/SparseLU_relax_snode.h \
    include/needed_algo/Eigen/src/SparseQR/SparseQR.h \
    include/needed_algo/Eigen/src/StlSupport/StdDeque.h \
    include/needed_algo/Eigen/src/StlSupport/StdList.h \
    include/needed_algo/Eigen/src/StlSupport/StdVector.h \
    include/needed_algo/Eigen/src/StlSupport/details.h \
    include/needed_algo/Eigen/src/SuperLUSupport/SuperLUSupport.h \
    include/needed_algo/Eigen/src/UmfPackSupport/UmfPackSupport.h \
    include/needed_algo/Eigen/src/misc/Image.h \
    include/needed_algo/Eigen/src/misc/Kernel.h \
    include/needed_algo/Eigen/src/misc/RealSvd2x2.h \
    include/needed_algo/Eigen/src/misc/blas.h \
    include/needed_algo/Eigen/src/misc/lapack.h \
    include/needed_algo/Eigen/src/misc/lapacke.h \
    include/needed_algo/Eigen/src/misc/lapacke_mangling.h \
    include/needed_algo/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
    include/needed_algo/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
    include/needed_algo/Eigen/src/plugins/BlockMethods.h \
    include/needed_algo/Eigen/src/plugins/CommonCwiseBinaryOps.h \
    include/needed_algo/Eigen/src/plugins/CommonCwiseUnaryOps.h \
    include/needed_algo/Eigen/src/plugins/IndexedViewMethods.h \
    include/needed_algo/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
    include/needed_algo/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
    include/needed_algo/Eigen/src/plugins/ReshapedMethods.h \
    include/needed_algo/common.h \
    include/needed_algo/covariance.hpp \
    include/needed_algo/dbscan.hpp \
    include/needed_algo/kmeans.hpp \
    include/needed_algo/leastsquare.hpp \
    include/needed_algo/pca.hpp \
    include/needed_algo/rowfeature.hpp \
    include/needed_algo/xgboost_example.h \
    widget.h \
    window_barchart.h \
    window_cluster.h \
    window_covariance.h \
    window_ml.h \
    window_pca.h \
    window_scatter.h

FORMS += \
    widget.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

RESOURCES += \
    resource.qrc

LIBS += -L$$PWD/xgboost/bin -lxgboost
INCLUDEPATH += $$PWD/xgboost/include
DEPENDPATH += $$PWD/xgboost/include
